apiVersion: v1
kind: Service
metadata:
  name: scrapeme-automation
  namespace: scrapeme
  labels:
    app: scrapeme
spec:
  type: ClusterIP
  selector:
    app: scrapeme
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
