apiVersion: v1
kind: Service
metadata:
  name: selenium-automation
  namespace: selenium-automation
  labels:
    app: selenium-automation
spec:
  type: ClusterIP
  selector:
    app: selenium-automation
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
