apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app.kubernetes.io/name: selenium-hub
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: selenium-hub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: selenium-hub
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1200
        runAsGroup: 1201
        fsGroup: 1201
      containers:
        - name: hub
          image: {{ .Values.hub.image }}
          ports:
            - containerPort: 4444
              name: hub
            - containerPort: 4442
              name: publish
            - containerPort: 4443
              name: subscribe
          env:
            - name: SE_SESSION_REQUEST_TIMEOUT
              value: "300"
            - name: SE_NODE_MAX_SESSIONS
              value: "5"
            - name: SE_SESSION_RETRY_INTERVAL
              value: "5"
          livenessProbe:
            httpGet:
              path: /status
              port: 4444
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /status
              port: 4444
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.hub.resources | nindent 12 }}
          volumeMounts:
            - name: dev-shm
              mountPath: /dev/shm
      volumes:
        - name: dev-shm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
spec:
  selector:
    app.kubernetes.io/name: selenium-hub
  ports:
    - name: hub
      port: 4444
      targetPort: 4444
    - name: publish
      port: 4442
      targetPort: 4442
    - name: subscribe
      port: 4443
      targetPort: 4443
