apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scrapeme-app.fullname" . }}-config
  labels:
    {{- include "scrapeme-app.labels" . | nindent 4 }}
data:
  {{ .Values.config.fileName }}: |
{{ .Values.config.sites | indent 4 }}
