apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scrapeme-app.fullname" . }}
  labels:
    {{- include "scrapeme-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "scrapeme-app.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "scrapeme-app.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.metrics.port }}"
        prometheus.io/path: "{{ .Values.metrics.path }}"
    spec:
      serviceAccountName: {{ include "scrapeme-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.port }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- if .Values.extraEnv }}
          envFrom:
            {{- toYaml .Values.extraEnvFrom | nindent 12 }}
          {{- end }}
          args: {{- toYaml .Values.args | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: {{ .Values.config.mountPath }}
              readOnly: true
            - name: artifacts
              mountPath: /app/artifacts
            - name: results
              mountPath: /app/results
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.metrics.port }}
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.metrics.port }}
            initialDelaySeconds: 10
            periodSeconds: 15
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: {{ include "scrapeme-app.fullname" . }}-config
            items:
              - key: {{ .Values.config.fileName }}
                path: {{ .Values.config.fileName }}
        - name: artifacts
          persistentVolumeClaim:
            claimName: {{ .Values.artifactsPVC.name }}
        - name: results
          persistentVolumeClaim:
            claimName: {{ .Values.resultsPVC.name }}
