apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "scrapeme-app.fullname" . }}
  labels:
    {{- include "scrapeme-app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "scrapeme-app.selectorLabels" . | nindent 6 }}
