{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "scrapeme-app.fullname" . }}
  labels:
    {{- include "scrapeme-app.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods","configmaps"]
    verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "scrapeme-app.fullname" . }}
  labels:
    {{- include "scrapeme-app.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "scrapeme-app.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "scrapeme-app.fullname" . }}
{{- end }}
