apiVersion: v1
kind: Service
metadata:
  name: {{ include "scrapeme-app.fullname" . }}
  labels:
    {{- include "scrapeme-app.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.metrics.port }}"
    prometheus.io/path: "{{ .Values.metrics.path }}"
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "scrapeme-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
