apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scrapeme-dev

resources:
  - ../../base

patchesStrategicMerge:
  - namespace-patch.yaml
  - resource-limits-patch.yaml
  - monitoring-patch.yaml

replicas:
  - name: scrapeme-app
    count: 1
  - name: selenium-chrome
    count: 1
  - name: prometheus
    count: 1

images:
  - name: scrapeme
    newTag: dev

commonLabels:
  environment: development
  
commonAnnotations:
  deployment.kubernetes.io/revision: "1"
  config.kubernetes.io/local-config: "true"

configMapGenerator:
  - name: dev-config
    literals:
      - LOG_LEVEL=DEBUG
      - ENABLE_DEBUG=true
      - MAX_WORKERS=2

patchesJson6902:
  - target:
      version: v2
      kind: HorizontalPodAutoscaler
      name: scrapeme-app-hpa
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
